#!/bin/bash

# inspired by https://github.com/sameersbn/docker-skype/blob/master/scripts/skype-wrapper

XSOCK=/tmp/.X11-unix
XAUTH=/tmp/.docker.xauth

touch ${XAUTH}
xauth nlist :0 | sed -e 's/^..../ffff/' | xauth -f ${XAUTH} nmerge -

docker run \
  --detach \
  --env=DISPLAY \
  --env=XAUTHORITY=${XAUTH} \
  --volume=${XSOCK}:${XSOCK} \
  --volume=${XAUTH}:${XAUTH} \
  --entrypoint=/usr/bin/PothosGui \
  philmd/pothos:latest $@
